[package]
name = "bootsector"
version = "0.1.0"
authors = ["Ryland Morgan <@rybot666>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stage_2 = { path = "../stage_2" }